### PR TITLE
Presigned URLs by default in GET file, bundle

### LINKED ISSUE #3: Use presigned URLs by default in getfile and getbundle
We should just reverse the defaults here instead of removing cloud native URLs. Make presingned URLs be the default.

### PR DESCRIPTION
**Pull request by natanlao**
Closes #3

All clear on [Travis](https://travis-ci.com/HumanCellAtlas/data-store/builds/144417021) and [GitLab](https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/pipelines/20598)

### CODE REVIEW

**Review by amarjandu — COMMENTED** [review]
This PR removes direct access URLS, the ticket is for just changing the default type to presigned.
From reading the old code-base it appears that presigned urls for the file endpoint is already the default, unless direct-urls are explicitly requested for. 

I've asked for more direction from Kevin about this ticket in the slack channel, maybe he can say here for record keeping. @kozbo 

I believe the original request for removing direct-access was to help get rid of checkout. If we remove checkout we would also want to remove direct access to the primary buckets, and maybe allow for bring your own bucket.

**Comment by kozbo** [comment]
Please see https://app.zenhub.com/workspaces/dss-5d557cb1ea5532000162e91c/issues/humancellatlas/data-store/2100
for context

**Comment by natanlao** [comment]
Ah, that's my bad.

**Comment by natanlao** [comment]
In this case, it looks like presigned URLs are the default for GET file, and I'll make the one-line change to make it the default for GET bundle.

**Comment by natanlao** [comment]
Change no longer required. https://github.com/DataBiosphere/data-store/issues/3#issuecomment-577882597

**Pull request closed without merging**
