### PR TITLE
Remove stage-specific environment variables

### PR DESCRIPTION
**Pull request by chmreid**
Housekeeping in the environment file...

Removes environment variables (mostly bucket-related) ending with `_STAGING`, `_INTEGRATION`, or `_PROD` from the environment file

### CODE REVIEW

**Comment by amarjandu** [comment]
we can remove them, but lets throw in a comment to the hca/data-store env file to look at one if someone needs a reference for multiple stages.

**Comment by chmreid** [comment]
Good thinking.

Forgot that these are also referenced in the terraform files, so am taking care of those too.

**Comment by chmreid** [comment]
Commit ff4cbff adds info about multi-stage deployments to the readme and a few comments in the environment file

**Review by amarjandu — APPROVED** [review]
Looks good, thanks for adding the reference to the HCA deployment

**Pull request merged**
